query ReposReleases($ids: [ID!]!, $count: Int!) {
	nodes(ids: $ids) {
		... on Repository {
			id
			name
			nameWithOwner
			url
			owner {
				avatarUrl
			}
			releases(last: $count) {
				nodes {
					id
					name
					description
					publishedAt
					url
					author {
						avatarUrl
						name
					}
				}
			}
		}
	}
}
