query ReposReleases($ids: [ID!]!, $count: Int!) {
	nodes(ids: $ids) {
		... on Repository {
			id
			name
			nameWithOwner
			releases(last: $count) {
				nodes {
					id
					name
					description
					publishedAt
					url
				}
			}
		}
	}
}
